### PR TITLE
Send empty chunk when a chunk is lost

### PR DESCRIPTION
**Pull request by hehaichi**
The current implementation does not send any chunk at all if the chunk is lost. Here, an empty chunk is sent. This ensures that there is a continuity when the next chunk arrives.

Also, there are 13 commits shown here. That was when I implemented the tracker in the core repository. Since then I've moved it to the p2psp-console repository. Only the last commit is of relevance here!

Thanks!

### CODE REVIEW

**Comment by hehaichi** [comment]
I should have done a ```git stash``` before committing. That would remove all the unnecessary details about the tracker :sweat_smile:

**Comment by vicente-gonzalez-ruiz** [comment]
@hehaichi, thanks for your PR! Please, let we check this contribution carefully (it affects directly to the most basic behavior of the rendering procedure).

**Comment by vicente-gonzalez-ruiz** [comment]
Hi again. Your contribution works perfectly. However, I would like to request you to minimal modifications: (1) the chunk size is not always 1024 (there is a variable with this information) and (2) could we avoid using an `if` statement if we have always the position -1 of the buffer with an empty chunk?

**Comment by hehaichi** [comment]
We can't do that as the buffer keeps changing (at an interval defined by buffer size). Another better option is to have a separate function handle the empty chunk case

**Comment by vicente-gonzalez-ruiz** [comment]
@hehaichi, I don't understand you. The buffer size if a constant defined by the splitter (all peers of the team have the same buffer size all the time the team exists) with peers join. Neither I can't figure out what are you proposing in your second sentence. Could you provide an example? Thanks!!

**Comment by hehaichi** [comment]
What I meant to say is that the buffer keeps changing with new chunks. So where to store the empty chunk? What I propose is that, we have a new function to send the empty chunk itself and this function is called whenever the chunk is lost

**Comment by vicente-gonzalez-ruiz** [comment]
I propose to store the empty chunk at the position -1 of the buffer (this a chunk index that never is received in a chunk) and use the `played_chunk_` variable to determine which chunk is going to be played. If you want to try these changes, go ahead. However, your actual proposal is OK. I'll wait for a while to know if you want to try this before I merge your PR. Thanks!

**Comment by hehaichi** [comment]
@vicente-gonzalez-ruiz , the buffer in this case is a char vector ```chunks_```. I don't understand how to store the empty chunk at position -1. Do you mean ```chunks_[-1]```?

**Comment by vicente-gonzalez-ruiz** [comment]
Right. In C (and I suppose in C++) if you allocate a block of memory of size N+1 and next, you increment the returned pointer ptr by 1, if you use ptr[-1] you are accessing the first element of the block. I'm thinking about using the `received` array (that now stores true or false) to store the position of the chunk. If we do that, we will know if a chunk has been received or not because only those received chunks will have an index != -1. But, again, we can, we can leave this for the future if you see that can't be done (I'm only supposing that). Regards.

**Comment by hehaichi** [comment]
So, what are the changes you propose? On another note, I've started coding the synchronizer!

**Comment by vicente-gonzalez-ruiz** [comment]
Basically, use the `received` table to store the position of the chunks in the buffer (now, the position is computed as `chunk_index % buffer_size`. The idea is to do the same, but these values should be stored in `received`, and if an entry (in `received`) references the position -1, this is because this chunk has not been received.

@hehaichi, thanks for your work!!

**Comment by hehaichi** [comment]
@vicente-gonzalez-ruiz , even if the ```received``` variable of each ```Chuck``` structure stores the chunk index, how do we address the ```chunks_``` vector? The chunk indices can be stored in ```received``` variable but how will it be used further?

**Comment by hehaichi** [comment]
@vicente-gonzalez-ruiz , the chunk index is stored in ```received``` now.

**Comment by vicente-gonzalez-ruiz** [comment]
Thanks @hehaichi :-)

**Pull request merged**
