### PR TITLE
Implementation of tracker

### PR DESCRIPTION
**Pull request by hehaichi**
@vicente-gonzalez-ruiz 
Please review the code and tell me if there is any correction to be made. 
I have put a comment about attaching headers. If there is a better way, do let me know :smile: 
Do let me know if the implementation is correct

### CODE REVIEW

**Comment by vicente-gonzalez-ruiz** [comment]
Hi @hehaichi! Thanks for your PR. I have not analyzed your code (still), because I'm not sure if the best place for the tracker is the core repository. What do you think about adding the tracker to the p2psp-console repository?

**Comment by hehaichi** [comment]
Sounds great! But then this functionality will be limited to only the console version. If this feature is not required for other versions, then fine!

**Comment by vicente-gonzalez-ruiz** [comment]
For console is enough. The other implementations are for "front-end" devices and probably they never will need to run a tracker.

**Comment by hehaichi** [comment]
You will shortly receive a PR at p2psp-console repository!

**Pull request closed without merging**
